name: flutter_local_notifications_example
description: Demonstrates how to use the flutter_local_notifications plugin.
publish_to: "none"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications_tizen:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
