name: flutter_local_notifications_tizen
description: The tizen implementation of flutter_local_notifications plugin.
homepage: https://github.com/flutter-tizen/plugins
repository: https://github.com/flutter-tizen/plugins/tree/master/packages/flutter_local_notifications
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.1.5

flutter:
  plugin:
    platforms:
      tizen:
        pluginClass: FlutterLocalNotificationsPlugin
        fileName: flutter_local_notifications_plugin.h

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
